### ISSUE TITLE
I see process but cant send keys

### ISSUE THREAD

**Issue by write4alive** [TommasoBelluzzo/MacroUO#2]
I can see process and select it but it wont send keys. The target windows can be minimized ? should the target be thet top most  window?

**Comment by TommasoBelluzzo** [comment]
Hi @write4alive, sorry for the delay in my reply. As far as I can tell, the application works even on non-topmost or minimized windows, you can verify by yourself using Spy++. May I have more details about what you are attempting to do? What is your operating system version? Are you running MacroUO with elevated privileges?
